import { useState, useRef, useEffect, useCallback } from "react";
import Markdown from "react-markdown";
import { streamChat, uploadFiles, fileUrl, type ChatEvent, type FileMeta } from "./api";

interface Message {
  role: "user" | "assistant";
  content: string;
  tools?: { id: string; name: string; done: boolean; isError?: boolean }[];
  files?: FileMeta[];
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export default function Chat() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [isStreaming, setIsStreaming] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const [pendingFiles, setPendingFiles] = useState<FileMeta[]>([]);
  const abortRef = useRef<AbortController | null>(null);
  const bottomRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Auto-scroll to bottom
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  // Focus input on mount
  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  const handleFileUpload = useCallback(async (e: React.ChangeEvent<HTMLInputElement>) => {
    const selected = e.target.files;
    if (!selected || selected.length === 0) return;

    setIsUploading(true);
    try {
      const uploaded = await uploadFiles(Array.from(selected));

      // Add a user message showing the uploaded files as links
      const fileLinks = uploaded
        .map((f) => `[${f.originalName}](${fileUrl(f.filename)}) (${formatSize(f.size)})`)
        .join("\n");

      // Track as pending files — will be sent with the next chat message
      setPendingFiles((prev) => [...prev, ...uploaded]);

      setMessages((prev) => [
        ...prev,
        {
          role: "user",
          content: `Uploaded:\n${fileLinks}`,
          files: uploaded,
        },
      ]);
    } catch (err: any) {
      setMessages((prev) => [
        ...prev,
        { role: "assistant", content: `**Upload failed:** ${err.message}` },
      ]);
    } finally {
      setIsUploading(false);
      e.target.value = ""; // Reset input
    }
  }, []);

  const handleSend = useCallback(() => {
    const text = input.trim();
    if (!text || isStreaming) return;

    // Grab pending files and clear them
    const filesToSend = [...pendingFiles];
    setPendingFiles([]);
    setInput("");
    setIsStreaming(true);

    // Add user message (with file attachment note if any) + empty assistant message
    const displayText = filesToSend.length > 0
      ? `${text}\n\n*Attached: ${filesToSend.map((f) => f.originalName).join(", ")}*`
      : text;

    setMessages((prev) => [
      ...prev,
      { role: "user", content: displayText, files: filesToSend.length > 0 ? filesToSend : undefined },
      { role: "assistant", content: "", tools: [] },
    ]);

    const controller = streamChat(
      text,
      (event: ChatEvent) => {
      setMessages((prev: Message[]) => {
        const updated = [...prev];
        const last = { ...updated[updated.length - 1]! };
        last.tools = [...(last.tools ?? [])];

        switch (event.type) {
          case "text_delta":
            last.content += event.delta;
            break;
          case "tool_start":
            last.tools.push({
              id: event.id,
              name: event.name,
              done: false,
            });
            break;
          case "tool_end":
            last.tools = last.tools.map((t) =>
              t.id === event.id
                ? { ...t, done: true, isError: event.isError }
                : t,
            );
            break;
          case "files_updated": {
            // Append download links for files generated by tools
            const links = event.files
              .map((f) => `- [${f.filename}](${fileUrl(f.filename)}) (${formatSize(f.size)})`)
              .join("\n");
            last.content += `\n\n**Generated files:**\n${links}`;
            last.files = [...(last.files ?? []), ...event.files];
            break;
          }
          case "done":
            setIsStreaming(false);
            break;
          case "error":
            last.content += `\n\n**Error:** ${event.error}`;
            setIsStreaming(false);
            break;
        }

        updated[updated.length - 1] = last;
        return updated;
      });
    },
      filesToSend.length > 0 ? filesToSend : undefined,
    );

    abortRef.current = controller;
  }, [input, isStreaming, pendingFiles]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div className="flex flex-col h-full">
      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 py-6 space-y-4">
        {messages.length === 0 && (
          <div className="text-center text-gray-400 mt-20">
            <p className="text-2xl font-semibold mb-2">civilclaw</p>
            <p className="text-sm">
              AEC intelligence. Ask about structural analysis, building codes,
              cost estimation, energy modeling, or anything else.
            </p>
          </div>
        )}

        {messages.map((msg, i) => (
          <div
            key={i}
            className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
          >
            <div
              className={`max-w-[80%] rounded-2xl px-4 py-3 ${
                msg.role === "user"
                  ? "bg-blue-600 text-white"
                  : "bg-gray-100 text-gray-900"
              }`}
            >
              {/* Tool indicators */}
              {msg.tools && msg.tools.length > 0 && (
                <div className="flex flex-wrap gap-1.5 mb-2">
                  {msg.tools.map((tool) => (
                    <span
                      key={tool.id}
                      className={`inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded-full ${
                        tool.isError
                          ? "bg-red-100 text-red-700"
                          : tool.done
                            ? "bg-green-100 text-green-700"
                            : "bg-yellow-100 text-yellow-700"
                      }`}
                    >
                      {!tool.done && (
                        <span className="inline-block w-2 h-2 rounded-full bg-current animate-pulse" />
                      )}
                      {tool.name}
                    </span>
                  ))}
                </div>
              )}

              {/* Message content */}
              {msg.role === "assistant" ? (
                <div className="prose prose-sm max-w-none prose-gray">
                  <Markdown>{msg.content || (isStreaming && i === messages.length - 1 ? "..." : "")}</Markdown>
                </div>
              ) : (
                <div className="whitespace-pre-wrap">
                  <Markdown
                    components={{
                      // Make links in user messages (uploaded file links) visible on blue bg
                      a: ({ children, href, ...props }) => (
                        <a
                          href={href}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="underline text-blue-100 hover:text-white"
                          {...props}
                        >
                          {children}
                        </a>
                      ),
                    }}
                  >
                    {msg.content}
                  </Markdown>
                </div>
              )}
            </div>
          </div>
        ))}

        <div ref={bottomRef} />
      </div>

      {/* Input */}
      <div className="border-t border-gray-200 px-4 py-3 bg-white">
        {/* Pending files indicator */}
        {pendingFiles.length > 0 && (
          <div className="flex flex-wrap gap-1.5 mb-2 max-w-4xl mx-auto">
            {pendingFiles.map((f, i) => (
              <span
                key={i}
                className="inline-flex items-center gap-1 text-xs bg-blue-50 text-blue-700 px-2 py-1 rounded-lg"
              >
                {f.originalName}
                <button
                  onClick={() => setPendingFiles((prev) => prev.filter((_, j) => j !== i))}
                  className="text-blue-400 hover:text-blue-600 ml-0.5"
                >
                  x
                </button>
              </span>
            ))}
          </div>
        )}
        <div className="flex items-end gap-2 max-w-4xl mx-auto">
          {/* File upload button */}
          <button
            onClick={() => fileInputRef.current?.click()}
            disabled={isStreaming || isUploading}
            className="rounded-xl bg-gray-100 text-gray-600 px-3 py-2.5 text-sm hover:bg-gray-200 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
            title="Upload files"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13" />
            </svg>
          </button>
          <input
            ref={fileInputRef}
            type="file"
            multiple
            className="hidden"
            onChange={handleFileUpload}
          />
          <textarea
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Ask civilclaw..."
            rows={1}
            className="flex-1 resize-none rounded-xl border border-gray-300 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            disabled={isStreaming}
          />
          <button
            onClick={handleSend}
            disabled={isStreaming || !input.trim()}
            className="rounded-xl bg-blue-600 text-white px-4 py-2.5 text-sm font-medium hover:bg-blue-700 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
          >
            {isStreaming ? "..." : "Send"}
          </button>
        </div>
      </div>
    </div>
  );
}
